# THIS FILE WILL BE RAN BY MAIN PROGRAM TO STAY OPEN FOR COMMS FROM PROC MGMT PORT #
# WILL REFORMAT MESSAGE FROM THAT GROUP FOR THE STORAGE MGMT GROUP AND THEN FORWARD IT TO THEIR PORT #
# HANDS OFF, NO USER INPUT NECESSARY